developed createOrderEndPoint
translense-private-limited/styler-backend pull request #36
Opened 2024-11-29 14:51 UTC by Prasanthi-Translense

## What does this pull request do?

Any additional comments that the developer wants to add.

## Does this pull request meet the acceptance criteria?

*To be updated by the maintainer/code reviewer processing a pull request.*

### Conformity
**1) Developer**
- [ ] Documentation and Update README.md.
- [ ] No custom linter rules are added and all code linting rules are passed.
- [ ] Postman Collection update
- [ ] Postman collection PR send

**Reviewer**
- [ ] Postman collection reviewed

### Availability and Testing

- [ ] Project must build successfully
- [ ] All test cases are passed

2024-11-29 15:12 UTC, translense-atul requested changes

2024-11-29 15:12 UTC, translense-atul commented on src/modules/client/services/services/service-external.ts
file name need to be service-external.service.ts

2024-11-29 15:12 UTC, translense-atul commented on src/modules/client/services/services/service-external.ts
> +        // });
remove the content

2024-11-29 15:12 UTC, translense-atul commented on src/modules/client/services/services/service-external.ts
> +          console.log(serviceDetails)
remove ti

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/dtos/create-order.dto.ts
> +export class CreateOrderDto implements CreateOrderInterface{
you need required to create the createOrderInterface, instead you can create the orderinterface . '
and utilise it

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/dtos/create-order.dto.ts
> +    paymentId:string;
paymentid is not required

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/dtos/create-order.dto.ts
> +
add outletId also if you donot have

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/dtos/services.dto.ts
> +    serviceId:string;
this will be present in item table not here

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/order-item.entity.ts
> +  updatedAt: Date; // Timestamp of order item update
remove it, it will be added automatically

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/order-item.entity.ts
> +
add orderId

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/orders.entity.ts
> +  orderId: string; // Primary key for the order
make it number

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/orders.entity.ts
> +  price: number; // Total price of the order
amountPaid ,

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/orders.entity.ts
> +  paymentId: string; // ID of the payment transaction
payment id should not be present here

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/entities/orders.entity.ts
> +  updatedAt: Date; // Timestamp of order update
created at and updated at will be will be added automatically , 

you need to extend base enity

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/interfaces/create-order.interface.ts
> +  paymentId: string;
remove payment id

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/interfaces/services.interface.ts
> +
interface name is not correct, as per the fucntionality is contains

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +        const {services,customerId,paymentId} = createOrderDto;
payment id is not required

2024-11-29 15:12 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +                serviceId,quantity,discount:discount,notes,
check and improve the logic

2024-11-29 16:18 UTC, Prasanthi-Translense commented on src/modules/customer/order/dtos/create-order.dto.ts
> +    paymentId:string;
should I remove it? or make it optional?

2024-11-30 03:44 UTC, Prasanthi-Translense commented on src/modules/customer/order/dtos/services.dto.ts
> +    serviceId:string;
yeah sir but this dto is for response payload

2024-11-30 09:24 UTC, translense-atul requested changes

2024-11-30 09:24 UTC, translense-atul commented on src/modules/client/services/services/service-external.service.ts
>            throw new NotFoundException('Service not found for the given outlet and whitelabel');
this is not right approcah, you need to have whitelabe while querring the service.

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/controllers/customer.controller.ts
> +  // }
delete thid file if not used any where

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/dtos/create-order.dto.ts
> +    paymentId:string;
remove it , 
you havenot made it optionaly also

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/entities/order-item.entity.ts
> +  discount: number; // Discount applied to this order item
make it optional

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/entities/orders.entity.ts
> +  customerId: number; // ID of the customer placing the order
add outlet id

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/interfaces/create-order.interface.ts
> +  paymentId: string;
make it optional or remvoe it

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/interfaces/order.interface.ts
> +    paymentId:number;
maek it optinal

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/interfaces/ordered-services-details.interface.ts
> +export interface OrderedServicesDetailsInterface {
order-item interface will make more sense

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +
use the concept. of transaction

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +  private async processService(service: any, customer: CustomerDecoratorDto) {
any is not allowed

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +    const { serviceTotal, endTime } = this.calculateServiceDetails(price, discount, duration, quantity, startTime);
single funciton sngle reaponsibility

2024-11-30 09:24 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +    const orderItem = this.createOrderItem(serviceId, quantity, discount, notes);
have differnt service file for order item

2024-11-30 11:42 UTC, translense-atul requested changes

2024-11-30 11:42 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +  const { services, customerId, outletId, paymentId } = createOrderDto;
rename it orderItems

2024-11-30 11:42 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +  const orderedServices: OrderItemDto[] = [];
bit confussing

2024-11-30 11:42 UTC, translense-atul commented on src/modules/customer/order/services/order.service.ts
> +    const { serviceTotal, orderItem, orderedService } = await this.processService(service, customer);
process service is not appropiate

2024-12-03 19:13 UTC, merged