Admin authentication
translense-private-limited/styler-backend pull request #43
Opened 2024-12-05 14:36 UTC by Prasanthi-Translense

## What does this pull request do?

Any additional comments that the developer wants to add.

## Does this pull request meet the acceptance criteria?

*To be updated by the maintainer/code reviewer processing a pull request.*

### Conformity
**1) Developer**
- [ ] Documentation and Update README.md.
- [ ] No custom linter rules are added and all code linting rules are passed.
- [ ] Postman Collection update
- [ ] Postman collection PR send

**Reviewer**
- [ ] Postman collection reviewed

### Availability and Testing

- [ ] Project must build successfully
- [ ] All test cases are passed

2024-12-05 15:30 UTC, translense-atul requested changes

2024-12-05 15:30 UTC, translense-atul commented on src/modules/admin/services/admin.service.ts
> +    }
I believe this is also use somewhere else, so such function can me made global and used everywhere probably in utils module

2024-12-05 15:30 UTC, translense-atul commented on src/modules/admin/services/admin.service.ts
> +        const admin = await this.getAdminByEmailOrContactNumber(username);
Here utilise throwone method to reduce duplicate coding

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/dtos/admin-signup.dto.ts
> +  export class AdminSignupDto {
Implement interface

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/dtos/admin-token-payload.dto.ts
> +export class CustomerTokenPayloadDto implements AdminTokenPayloadInterface {
Class name correct it

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/interfaces/admin-token-payload.interface.ts
> +export interface AdminTokenPayloadInterface {
In entire flow i believe you missed the role

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +        console.log(this.adminExternalService)
Remove console

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +        if(adminByContactNumber|| adminByEmail){
As this is admin things give proper information conflict have occurrd because of number or email

2024-12-05 15:30 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +        await this.otpService.deleteByRecipient(
While registering we are not using otp things for admin, so we are not inserting so no deletion

2024-12-06 08:21 UTC, translense-atul requested changes

2024-12-06 08:21 UTC, translense-atul commented on src/modules/admin/services/admin.service.ts
> +        const isAdminExistWithContactNumber =
Changes as suggested over call

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/dtos/admin-signup.dto.ts
> +    roleId: number;
Check

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/interfaces/admin-login-response.interface.ts
> +    admin: Omit<AdminDto, 'password'>;
Give role name and role id also

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/interfaces/admin-login-response.interface.ts
> +    admin: Omit<AdminDto, 'password'>;
Add role details

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/interfaces/admin-token-payload.interface.ts
> +export interface AdminTokenPayloadInterface {
Add roleid

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +        const adminByContactNumber =
Fix as suggested over call

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +          contactNumber: admin.contactNumber,
Add roleid

2024-12-06 08:21 UTC, translense-atul commented on src/modules/authentication/services/admin-auth.service.ts
> +    async adminLogin(
Login needs to be public

2024-12-06 09:06 UTC, Prasanthi-Translense commented on src/modules/admin/entities/admin.entity.ts
> +  @Column()
that's not 2nd time sir it indicates roleId will add line space

2024-12-06 09:07 UTC, Prasanthi-Translense commented on src/modules/admin/seed/data/admin.data.ts
> +                    name: 'Super Admin',
it is for admin only sir

2024-12-06 09:19 UTC, Prasanthi-Translense commented on src/modules/authentication/services/admin-auth.service.ts
> +    async adminLogin(
both login and signup already set to public sir

2024-12-07 03:06 UTC, merged